name: ci-cd
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Restore dependencies
        run: dotnet restore ./Ecommerce/Ecommerce.sln
      - name: Build
        run: dotnet build --configuration Release ./Ecommerce/Ecommerce.sln
      - name: Run tests
        run: dotnet test --no-build --verbosity normal ./Ecommerce/Ecommerce.sln
  docker-build:
    runs-on: windows-latest
    steps:
      - name: Build Docker GatewayService
        run: docker build -t gatewayservice-image -f ./Ecommerce/GatewayService/Dockerfile .
      - name: Print working directory
        run: pwd
      - name: Build Docker OrderService
        run: docker build -t orderservice-image -f ./OrderService/Dockerfile ./OrderService
      - name: Build Docker ProductService
        run: docker build -t productservice-image -f ./ProductService/Dockerfile ./ProductService
