name: ci-cd
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Restore dependencies
        run: dotnet restore ./Ecommerce/Ecommerce.sln
      - name: Build
        run: dotnet build --configuration Release ./Ecommerce/Ecommerce.sln
      - name: Run tests
        run: dotnet test --no-build --verbosity normal --configuration Release ./Ecommerce/Ecommerce.sln
  docker-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REPOSITORY: ${{ github.repository }}
    steps:
      - name: Congigure jov
        run:  echo "REPOSITORY=$(echo $REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Get Code
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker GatewayService
        run: |
            docker build --platform linux/amd64 -t ghcr.io/${REPOSITORY}/gatewayservice-image:latest -f ./Ecommerce/GatewayService/Dockerfile ./Ecommerce/GatewayService/
            docker push ghcr.io/${REPOSITORY}/gatewayservice-image:latest
      - name: Build Docker OrderService
        run: |
            docker build --platform linux/amd64 -t ghcr.io/${REPOSITORY}/orderservice-image:latest -f ./Ecommerce/OrderService/Dockerfile ./Ecommerce
            docker push ghcr.io/${REPOSITORY}/orderservice-image:latest
      - name: Build Docker ProductService
        run: |
            docker build --platform linux/amd64 -t ghcr.io/${REPOSITORY}/productservice-image:latest -f ./Ecommerce/ProductService/Dockerfile ./Ecommerce/ProductService
            docker push ghcr.io/${REPOSITORY}/productservice-image:latest
