name: ci-cd
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Restore dependencies
        run: dotnet restore ./Ecommerce/Ecommerce.sln
      - name: Build
        run: dotnet build --configuration Release ./Ecommerce/Ecommerce.sln
      - name: Run tests
        run: dotnet test --no-build --verbosity normal --configuration Release ./Ecommerce/Ecommerce.sln
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Build Docker GatewayService
        run: |
            repository=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
            echo "$repository"
            docker build --platform linux/amd64 -t ghcr.io/${repository}/gatewayservice-image:latest -f ./Ecommerce/GatewayService/Dockerfile ./Ecommerce/GatewayService/
            docker push --platform linux/amd64 -t ghcr.io/${repository}/gatewayservice-image:latest

      - name: Build Docker OrderService
        run: docker build --platform linux/amd64 -t orderservice-image -f ./Ecommerce/OrderService/Dockerfile ./Ecommerce
      - name: Build Docker ProductService
        run: docker build --platform linux/amd64 -t productservice-image -f ./Ecommerce/ProductService/Dockerfile ./Ecommerce/ProductService

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and tag Docker image
        run: |
            repository=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
            echo "$repository"
            docker build -t ghcr.io/${repository}/gatewayservice-image:latest .
