name: ci-cd
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore dependencies
        run: dotnet restore ./Ecommerce/Ecommerce.sln
      - name: Build
        run: dotnet build --configuration Release ./Ecommerce/Ecommerce.sln

